# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rake", "~> 13.0"

gem "sqlite3", "~> 1.6"

gem "sinatra-activerecord", "~> 2.0"

gem "require_all", "~> 3.0"

gem "pry", "~> 0.14.2"

gem "activerecord", "~> 7.0"

gem "sinatra", "~> 3.0"

gem "rake-contrib", "~> 1.0"

gem "thin", "~> 1.8"

gem "rails", "~> 7.0"
